### ISSUE TITLE
panic: state.go:166

### ISSUE THREAD

**Issue by meowsbits** [ziogaschr/supply-tracer-parser#1]
```sh
_leif 04-05_13:55:42 ~/dev/ziogaschr/supply-tracer-parser main %=
python3 ./mock_generator.py                                                                                                
_mesa 04-05_13:55:50 ~/dev/ziogaschr/supply-tracer-parser main %=
head -1 mock.jsonl > mock-2026-03xyz.jsonl                                                                                 
_smog 04-05_13:55:54 ~/dev/ziogaschr/supply-tracer-parser main %=
cat mock.jsonl | tail -n +2 > mock.jsonl.tmp && mv mock.jsonl.tmp mock.jsonl                                               
_teat 04-05_13:56:08 ~/dev/ziogaschr/supply-tracer-parser main %=
./supply-tracer-parser --supply.file ./mock.jsonl                                                                          
2024/04/05 13:56:12 Loaded state from file state.json
2024/04/05 13:56:12 Starting server on :8080
_buck 04-05_13:56:13 ~/dev/ziogaschr/supply-tracer-parser main %=
./supply-tracer-parser --supply.file ./mock.jsonl 
2024/04/05 13:56:16 Loaded state from file state.json
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x79490a]

goroutine 7 [running]:
main.(*State).rewindTo(0x0?, 0xc000064a08?, {0xe2, 0x2, 0x4b, 0xdb, 0x18, 0x10, 0xc6, 0xbc, ...}, ...)
        /home/ia/dev/ziogaschr/supply-tracer-parser/state.go:166 +0xaa
main.(*State).handleEntry(0xc0001be090, {0xc000128000, 0xc000128020, 0xc000128040, 0xc000128060, 0x2, {0x9a, 0x10, 0x4d, 0x77, ...}, ...}, ...)
        /home/ia/dev/ziogaschr/supply-tracer-parser/state.go:138 +0xe9
main.run.func1()
        /home/ia/dev/ziogaschr/supply-tracer-parser/main.go:59 +0x190
created by main.run in goroutine 1
        /home/ia/dev/ziogaschr/supply-tracer-parser/main.go:56 +0x31a
```

Attached `mock*.json` files are renamed from their original `*.jsonl` extensions because Github won't support uploading `jsonl`. Files unchanged otherwise.

[state.json](https://github.com/ziogaschr/supply-tracer-parser/files/14890231/state.json)
[mock-2026-03xyz.json](https://github.com/ziogaschr/supply-tracer-parser/files/14890236/mock-2026-03xyz.json)
[mock.json](https://github.com/ziogaschr/supply-tracer-parser/files/14890237/mock.json)

**Comment by ziogaschr** [comment]
I just tested it and run without issues.

```
 ~/Sites/etclabs/supply-reader :: main ≢  ?10 ~3 |   |  100  | 18:28:53  
➜ python3 ./mock_generator.py
 ~/Sites/etclabs/supply-reader :: main ≢  ?11 ~3 |   | 98  | 23:06:05  
➜ head -1 mock.jsonl > mock-2026-03xyz.jsonl
 ~/Sites/etclabs/supply-reader :: main ≢  ?12 ~3 |   | 98  | 23:06:21  
➜ cat mock.jsonl | tail -n +2 > mock.jsonl.tmp && mv mock.jsonl.tmp mock.jsonl
 ~/Sites/etclabs/supply-reader :: main ≢  ?12 ~3 |   | 98  | 23:06:57  
➜ ./supply-tracer-parser --supply.file ./mock.jsonl
2024/04/06 23:07:07 state file reading: open state.json: no such file or directory
2024/04/06 23:07:07 Starting server on :8080
^C2024/04/06 23:07:34 Received signal "interrupt", exiting...
 ~/Sites/etclabs/supply-reader :: main ≢  ?13 ~3 |   | 97  | 23:07:34  
➜ ./supply-tracer-parser --supply.file ./mock.jsonl
2024/04/06 23:07:36 Loaded state from file state.json
2024/04/06 23:07:36 Starting server on :8080
```

Can I ask why your uploaded files end in `*.json` and not `*.jsonl`. Can it be that you have both in your system?

**Comment by ziogaschr** [comment]
@meowsbits  can you check again, I made a new push.

**Comment by meowsbits** [comment]
> Attached mock*.json files are renamed from their original *.jsonl extensions because Github won't support uploading jsonl. Files unchanged otherwise.


With only a `git pull && go build` (not regenerating any files), I got this:

```
_turd 04-10_09:09:48 ~/dev/ziogaschr/supply-tracer-parser main %=                                               
./supply-tracer-parser --supply.file ./mock.jsonl                                                                          2024/04/10 09:09:53 Loaded state from file state.json                                                                      
2024/04/10 09:09:53 Starting server on :8080                                                                               panic: runtime error: invalid memory address or nil pointer dereference                                         
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x7958a6]                                                                                                                                                                                
goroutine 20 [running]:                                                                                                    main.(*State).forwardTo(0x5?, 0x0?, {0x9a, 0x10, 0x4d, 0x77, 0x7b, 0xc, 0x38, 0xd5, ...}, ...)                  
        /home/ia/dev/ziogaschr/supply-tracer-parser/state.go:308 +0xa6                                                     main.(*State).handleEntry(0xc0001ba090, {0xc0000a00a0, 0xc0000a00c0, 0xc0000a00e0, 0xc0000a0100, 0x3, {0x34, 0x85, 0x4f, 0x
aa, ...}, ...}, ...)                                                                                                               /home/ia/dev/ziogaschr/supply-tracer-parser/state.go:180 +0x16e                                         
main.run.func1()                                                                                                                   /home/ia/dev/ziogaschr/supply-tracer-parser/main.go:59 +0x190                                           
created by main.run in goroutine 1                                                                                                 /home/ia/dev/ziogaschr/supply-tracer-parser/main.go:56 +0x31a   
```

I then run it a second time:

```
_desk 04-10_09:10:24 ~/dev/ziogaschr/supply-tracer-parser main %=
./supply-tracer-parser --supply.file ./mock.jsonl 
2024/04/10 09:10:29 Loaded state from file state.json
2024/04/10 09:10:29 Starting server on :8080
2024/04/10 09:10:29 Exiting due to error: cannot rewind to block hash 0xe2024bdb1810c6bc53040bb25b066138366d848000bda6bf848fa7333dc75281, it is not in history
```

**Comment by meowsbits** [comment]
I think that my complaint above may be spurious or strangely inherited from previous attempts.
I scripted a fresh test, and it seems to work normally:


```sh
_void 04-10_09:22:51 ~/dev/ziogaschr/supply-tracer-parser main %=
cat ./.ia/test.sh
#!/usr/bin/env bash

set -x

rm -f mock*.jsonl

python3 ./mock_generator.py

# Pull the first line of the mock data to a timestamped file, simulating file roll.
head -1 mock.jsonl > mock-2024-02xyz.jsonl

# Remove the first line of the mock data from the source file.
cat mock.jsonl | tail -n +2 > /tmp/mock.jsonl \
  && mv /tmp/mock.jsonl mock.jsonl

# Build the executable
go build -o supply-tracer-parser

# Run
./supply-tracer-parser --supply.file ./mock.jsonl
_mode 04-10_09:22:53 ~/dev/ziogaschr/supply-tracer-parser main %=
./.ia/test.sh
+ rm -f mock-2024-02xyz.jsonl mock.jsonl
+ python3 ./mock_generator.py
+ head -1 mock.jsonl
+ cat mock.jsonl
+ tail -n +2
+ mv /tmp/mock.jsonl mock.jsonl
+ go build -o supply-tracer-parser
+ ./supply-tracer-parser --supply.file ./mock.jsonl
2024/04/10 09:23:01 Loaded state from file state.json
2024/04/10 09:23:01 Starting server on :8080
```
